import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
import { jsPDF } from "https://cdn.skypack.dev/jspdf@2.5.2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface ReportData {
  babyName: string;
  dateRange: { start: string; end: string };
  locale?: string;
  feedingSummary: { total: number; avgPerDay: number; totalVolume?: number };
  sleepSummary: { totalHours: number; avgPerDay: number; nightSleeps: number; naps: number };
  dailyLogs: Array<{ date: string; feeds: number; sleepHours: number; diapers: number }>;
  milestones: string[];
  observations: string;
  excludedDays?: string[];
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const data: ReportData = await req.json();
    
    // Detect page size based on locale (Letter for US, A4 elsewhere)
    const isUS = data.locale?.startsWith('en-US');
    const pageSize = isUS ? 'letter' : 'a4';
    
    const pdf = new jsPDF('p', 'mm', pageSize);
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    
    // Margins: top/bottom 20mm, left/right 15mm, plus 7mm bottom padding before page break
    const margins = { top: 20, bottom: 20, left: 15, right: 15 };
    const contentWidth = pageWidth - margins.left - margins.right;
    const bottomPadding = 7; // ~25px additional padding before page break
    const maxY = pageHeight - margins.bottom - bottomPadding;
    
    let currentY = margins.top;
    let currentPage = 1;
    
    // Helper: Add footer to current page
    const addFooter = () => {
      const footerY = pageHeight - 12;
      pdf.setFontSize(8);
      pdf.setTextColor(100, 100, 100);
      pdf.text(
        `Generated by Parenting Partner • ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`,
        margins.left,
        footerY
      );
      pdf.text(
        'For clinical reference only — not a medical record',
        pageWidth - margins.right,
        footerY,
        { align: 'right' }
      );
      pdf.text(`Page ${currentPage}`, pageWidth / 2, footerY, { align: 'center' });
    };
    
    // Helper: Check if we need a new page
    const checkPageBreak = (requiredHeight: number) => {
      if (currentY + requiredHeight > maxY) {
        addFooter();
        pdf.addPage();
        currentPage++;
        currentY = margins.top;
        return true;
      }
      return false;
    };
    
    // Helper: Add section header
    const addSectionHeader = (title: string) => {
      checkPageBreak(20); // Ensure section header + first line fit
      pdf.setFontSize(14);
      pdf.setTextColor(110, 70, 120); // Plum accent
      pdf.setFont('helvetica', 'bold');
      pdf.text(title, margins.left, currentY);
      currentY += 8;
      pdf.setDrawColor(110, 70, 120);
      pdf.setLineWidth(0.5);
      pdf.line(margins.left, currentY, pageWidth - margins.right, currentY);
      currentY += 10; // Increased spacing after section header
    };
    
    // Helper: Add body text
    const addBodyText = (text: string, indent = 0) => {
      pdf.setFontSize(10);
      pdf.setTextColor(40, 40, 40);
      pdf.setFont('helvetica', 'normal');
      const lines = pdf.splitTextToSize(text, contentWidth - indent);
      for (const line of lines) {
        checkPageBreak(6);
        pdf.text(line, margins.left + indent, currentY);
        currentY += 6;
      }
    };
    
    // Title
    pdf.setFontSize(18);
    pdf.setTextColor(40, 40, 40);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Summary for Pediatrician', margins.left, currentY);
    currentY += 10;
    
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Child: ${data.babyName}`, margins.left, currentY);
    currentY += 6;
    pdf.text(`Period: ${data.dateRange.start} to ${data.dateRange.end}`, margins.left, currentY);
    currentY += 12;
    
    // Data integrity banner
    if (data.excludedDays && data.excludedDays.length > 0) {
      checkPageBreak(20);
      pdf.setFillColor(255, 250, 205); // Yellow background
      pdf.rect(margins.left, currentY - 5, contentWidth, 15, 'F');
      pdf.setFontSize(9);
      pdf.setTextColor(80, 60, 0);
      pdf.text(`Note: ${data.excludedDays.length} day(s) excluded from analysis`, margins.left + 3, currentY);
      currentY += 12;
    }
    
    // Feeding Summary
    addSectionHeader('Feeding Summary');
    addBodyText(`Total Feeds: ${data.feedingSummary.total}`);
    addBodyText(`Average Feeds per Day: ${data.feedingSummary.avgPerDay.toFixed(1)}`);
    if (data.feedingSummary.totalVolume !== undefined) {
      addBodyText(`Total Volume: ${data.feedingSummary.totalVolume} ml`);
    }
    currentY += 8;
    
    // Sleep Summary
    addSectionHeader('Sleep Summary');
    addBodyText(`Total Sleep: ${data.sleepSummary.totalHours.toFixed(1)} h`);
    addBodyText(`Average Sleep per Day: ${data.sleepSummary.avgPerDay.toFixed(1)} h`);
    addBodyText(`Night Sleeps: ${data.sleepSummary.nightSleeps}`);
    addBodyText(`Naps: ${data.sleepSummary.naps}`);
    currentY += 8;
    
    // Daily Log Summary (Table)
    addSectionHeader('Daily Log Summary');
    
    const tableHeaders = ['Date', 'Feeds', 'Sleep (h)', 'Diapers'];
    const colWidths = [contentWidth * 0.3, contentWidth * 0.23, contentWidth * 0.23, contentWidth * 0.24];
    
    const drawTableHeader = () => {
      pdf.setFillColor(110, 70, 120);
      pdf.rect(margins.left, currentY - 5, contentWidth, 8, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(9);
      let x = margins.left + 2;
      tableHeaders.forEach((header, i) => {
        pdf.text(header, x, currentY);
        x += colWidths[i];
      });
      currentY += 6;
    };
    
    checkPageBreak(20);
    drawTableHeader();
    
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(40, 40, 40);
    
    for (let i = 0; i < data.dailyLogs.length; i++) {
      const log = data.dailyLogs[i];
      
      // Check if we need new page (avoid orphan row)
      if (currentY + 12 > maxY) {
        addFooter();
        pdf.addPage();
        currentPage++;
        currentY = margins.top;
        drawTableHeader(); // Repeat header on new page
      }
      
      const isEven = i % 2 === 0;
      if (isEven) {
        pdf.setFillColor(245, 245, 245);
        pdf.rect(margins.left, currentY - 5, contentWidth, 8, 'F');
      }
      
      let x = margins.left + 2;
      pdf.text(log.date, x, currentY);
      x += colWidths[0];
      pdf.text(String(log.feeds || '—'), x, currentY);
      x += colWidths[1];
      pdf.text(log.sleepHours ? log.sleepHours.toFixed(1) : '—', x, currentY);
      x += colWidths[2];
      pdf.text(String(log.diapers || '—'), x, currentY);
      
      currentY += 6;
    }
    
    currentY += 8;
    
    // Milestones & Key Changes
    if (data.milestones && data.milestones.length > 0) {
      checkPageBreak(25); // Ensure section header + at least one line
      addSectionHeader('Milestones & Key Changes');
      data.milestones.forEach(milestone => {
        addBodyText(`• ${milestone}`, 5);
      });
      currentY += 8;
    }
    
    // Observations
    if (data.observations) {
      checkPageBreak(25);
      addSectionHeader('Observations');
      addBodyText(data.observations);
    }
    
    // Add footer to last page
    addFooter();
    
    // Generate PDF
    const pdfBytes = pdf.output('arraybuffer');
    
    return new Response(pdfBytes, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${data.babyName}-pediatrician-summary.pdf"`,
      },
    });
    
  } catch (error) {
    console.error('Error generating PDF:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
