import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
import { jsPDF } from "https://cdn.skypack.dev/jspdf@2.5.2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface ReportData {
  babyName: string;
  babyAge?: string;
  babyBirthday?: string;
  dateRange: { start: string; end: string };
  locale?: string;
  feedingSummary: { 
    total: number; 
    avgPerDay: number; 
    totalVolume: number;
    avgPerFeed: number;
    minVolume: number;
    maxVolume: number;
    firstSolidDate?: string;
  };
  sleepSummary: { 
    totalHours: number; 
    avgPerDay: number; 
    totalNaps: number;
    avgNapLength: string;
    napCountRange: string;
    napCountMedian: number;
    longestOvernight?: string;
    avgOvernight?: string;
    hasIncompleteData?: boolean;
  };
  diaperSummary?: {
    total: number;
    avgPerDay: number;
  };
  dailyLogs: Array<{ 
    date: string; 
    sleepHours: number;
    naps: number;
    feedVolume: number; 
    feeds: number;
  }>;
  milestones: string[];
  observations: string[];
  excludedDays?: string[];
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const data: ReportData = await req.json();
    
    // Detect page size based on locale (Letter for US, A4 elsewhere)
    const isUS = data.locale?.startsWith('en-US');
    const pageSize = isUS ? 'letter' : 'a4';
    
    const pdf = new jsPDF('p', 'mm', pageSize);
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    
    // Margins and colors matching WeeklyReport
    const margins = { top: 25, bottom: 25, left: 20, right: 20 };
    const contentWidth = pageWidth - margins.left - margins.right;
    const bottomPadding = 20;
    const maxY = pageHeight - margins.bottom - bottomPadding;
    const plumColor = [107, 77, 119]; // #6B4D77
    const grayText = [40, 40, 40];
    const lightGray = [107, 114, 128];
    
    let currentY = margins.top;
    let currentPage = 1;
    
    // Helper: Add footer to current page
    const addFooter = () => {
      const footerY = pageHeight - 15;
      pdf.setDrawColor(200, 200, 200);
      pdf.setLineWidth(0.3);
      pdf.line(margins.left, footerY - 5, pageWidth - margins.right, footerY - 5);
      
      pdf.setFontSize(8);
      pdf.setTextColor(...lightGray);
      pdf.setFont('helvetica', 'normal');
      
      pdf.text('Generated by Sprout - Baby Tracker', margins.left, footerY);
      pdf.text('For clinical reference only — not a medical record', margins.left, footerY + 4);
      
      const dateStr = new Date().toLocaleDateString('en-US', { 
        month: 'short', 
        day: 'numeric', 
        year: 'numeric' 
      }) + ' at ' + new Date().toLocaleTimeString('en-US', { 
        hour: 'numeric', 
        minute: '2-digit' 
      });
      pdf.text(dateStr, pageWidth - margins.right, footerY, { align: 'right' });
    };
    
    // Helper: Check if we need a new page
    const checkPageBreak = (requiredHeight: number) => {
      if (currentY + requiredHeight > maxY) {
        addFooter();
        pdf.addPage();
        currentPage++;
        currentY = margins.top;
        return true;
      }
      return false;
    };
    
    // Helper: Add section header (matching WeeklyReport style)
    const addSectionHeader = (title: string) => {
      checkPageBreak(15);
      pdf.setFontSize(11);
      pdf.setTextColor(...plumColor);
      pdf.setFont('helvetica', 'bold');
      pdf.text(title.toUpperCase(), margins.left, currentY);
      currentY += 8;
    };
    
    // Helper: Add body text
    const addBodyText = (text: string, isBold = false) => {
      pdf.setFontSize(9);
      pdf.setTextColor(...grayText);
      pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
      const lines = pdf.splitTextToSize(text, contentWidth);
      for (const line of lines) {
        checkPageBreak(5);
        pdf.text(line, margins.left, currentY);
        currentY += 5;
      }
    };
    
    // Helper: Add separator line
    const addSeparator = () => {
      checkPageBreak(8);
      pdf.setDrawColor(209, 213, 219); // gray-300
      pdf.setLineWidth(0.3);
      pdf.line(margins.left, currentY, pageWidth - margins.right, currentY);
      currentY += 8;
    };
    
    // ==== HEADER ====
    pdf.setFontSize(9);
    pdf.setTextColor(...lightGray);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Sprout - Baby Tracker', margins.left, currentY);
    currentY += 6;
    
    pdf.setFontSize(12);
    pdf.setTextColor(...grayText);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${data.babyName}${data.babyAge ? ` • ${data.babyAge}` : ''}`, margins.left, currentY);
    currentY += 6;
    
    if (data.babyBirthday) {
      pdf.setFontSize(8);
      pdf.setTextColor(...lightGray);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`(${data.babyBirthday})`, margins.left, currentY);
      currentY += 5;
    }
    
    pdf.setFontSize(14);
    pdf.setTextColor(...plumColor);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Summary for Pediatrician', margins.left, currentY);
    currentY += 7;
    
    pdf.setFontSize(9);
    pdf.setTextColor(...grayText);
    pdf.setFont('helvetica', 'normal');
    pdf.text(data.dateRange.start + ' – ' + data.dateRange.end, margins.left, currentY);
    currentY += 5;
    
    pdf.setFont('helvetica', 'italic');
    const summaryText = `Summary of feeding and sleep patterns logged during this period.`;
    const summaryLines = pdf.splitTextToSize(summaryText, contentWidth);
    summaryLines.forEach((line: string) => {
      pdf.text(line, margins.left, currentY);
      currentY += 5;
    });
    currentY += 5;
    
    // Outlier notice
    if (data.excludedDays && data.excludedDays.length > 0) {
      checkPageBreak(15);
      pdf.setFillColor(255, 251, 235); // amber-50
      pdf.roundedRect(margins.left, currentY - 4, contentWidth, 12, 2, 2, 'F');
      pdf.setFontSize(8);
      pdf.setTextColor(120, 53, 15); // amber-900
      pdf.setFont('helvetica', 'bold');
      pdf.text('Note: ', margins.left + 3, currentY);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Some days were excluded from calculations due to incomplete data: ${data.excludedDays.join(', ')}`, margins.left + 12, currentY);
      currentY += 10;
    }
    
    addSeparator();
    
    // ==== FEEDING SUMMARY ====
    addSectionHeader('Feeding Summary');
    const feedOzTotal = (data.feedingSummary.totalVolume / 29.5735).toFixed(1);
    const feedOzAvg = (data.feedingSummary.avgPerFeed / 29.5735).toFixed(1);
    
    addBodyText(`Total Feeds: ${data.feedingSummary.total}`, true);
    addBodyText(`Total Volume: ${data.feedingSummary.totalVolume.toFixed(0)} ml (${feedOzTotal} oz)`, true);
    addBodyText(`Average Per Feed: ${Math.round(data.feedingSummary.avgPerFeed)} ml (${feedOzAvg} oz)`, true);
    addBodyText(`Daily Range: ${data.feedingSummary.minVolume}-${data.feedingSummary.maxVolume} ml`, true);
    addBodyText(`Feeding Pattern: ${data.feedingSummary.avgPerDay.toFixed(1)} feeds/day average`, true);
    if (data.feedingSummary.firstSolidDate) {
      addBodyText(`Solids Introduced: ${data.feedingSummary.firstSolidDate}`, true);
    }
    currentY += 3;
    
    pdf.setFont('helvetica', 'bold');
    addBodyText('Notes: ', true);
    pdf.setFont('helvetica', 'normal');
    const volumeVariation = data.feedingSummary.maxVolume - data.feedingSummary.minVolume;
    const notesText = `Daily intake shows stable feeding frequency with ${volumeVariation > 300 ? 'moderate' : 'mild'} volume variation. No missed feeds or feeding intolerance reported.${data.feedingSummary.firstSolidDate ? ' Solid foods have been introduced.' : ''}`;
    const notesLines = pdf.splitTextToSize(notesText, contentWidth);
    notesLines.forEach((line: string) => {
      checkPageBreak(5);
      pdf.text(line, margins.left, currentY);
      currentY += 5;
    });
    currentY += 5;
    
    addSeparator();
    
    // ==== SLEEP SUMMARY ====
    addSectionHeader('Sleep Summary');
    addBodyText(`Total Sleep: ${data.sleepSummary.totalHours.toFixed(1)} h (avg ${data.sleepSummary.avgPerDay.toFixed(1)} h/day)${data.sleepSummary.hasIncompleteData ? ' (Data incomplete for some days)' : ''}`, true);
    addBodyText(`Total Naps: ${data.sleepSummary.totalNaps}`, true);
    addBodyText(`Average Nap Length: ${data.sleepSummary.avgNapLength}`, true);
    addBodyText(`Nap Count Range: ${data.sleepSummary.napCountRange} naps/day (median: ${data.sleepSummary.napCountMedian})`, true);
    if (data.sleepSummary.longestOvernight) {
      addBodyText(`Longest Overnight Sleep: ${data.sleepSummary.longestOvernight} (avg ${data.sleepSummary.avgOvernight})`, true);
    }
    currentY += 3;
    
    pdf.setFont('helvetica', 'bold');
    addBodyText('Notes: ', true);
    pdf.setFont('helvetica', 'normal');
    const sleepNotesText = `${data.sleepSummary.avgPerDay >= 10 ? 'Consistent overnight sleep (~10-11h) with' : 'Overnight sleep with'} daytime nap count ${data.sleepSummary.napCountRange.includes('-') ? 'showing variation' : 'relatively stable'}.`;
    const sleepNotesLines = pdf.splitTextToSize(sleepNotesText, contentWidth);
    sleepNotesLines.forEach((line: string) => {
      checkPageBreak(5);
      pdf.text(line, margins.left, currentY);
      currentY += 5;
    });
    currentY += 5;
    
    addSeparator();
    
    // ==== DIAPER SUMMARY ====
    if (data.diaperSummary && data.diaperSummary.total > 0) {
      addSectionHeader('Diaper Summary');
      addBodyText(`Total Diapers: ${data.diaperSummary.total}`, true);
      addBodyText(`Daily Average: ${data.diaperSummary.avgPerDay.toFixed(1)} diapers/day`, true);
      currentY += 5;
      addSeparator();
    }
    
    // ==== MILESTONES ====
    if (data.milestones && data.milestones.length > 0) {
      addSectionHeader('Milestones & Key Changes');
      checkPageBreak(10);
      
      pdf.setDrawColor(156, 163, 175);
      pdf.setLineWidth(0.5);
      pdf.line(margins.left, currentY - 2, pageWidth - margins.right, currentY - 2);
      pdf.line(margins.left, currentY + (data.milestones.length * 5) + 2, pageWidth - margins.right, currentY + (data.milestones.length * 5) + 2);
      currentY += 2;
      
      pdf.setFontSize(9);
      pdf.setTextColor(...grayText);
      pdf.setFont('helvetica', 'normal');
      
      data.milestones.forEach(milestone => {
        checkPageBreak(5);
        pdf.text(`- ${milestone}`, margins.left + 3, currentY);
        currentY += 5;
      });
      
      currentY += 5;
      addSeparator();
    }
    
    // ==== OBSERVATIONS ====
    addSectionHeader('Observations');
    pdf.setFontSize(9);
    pdf.setTextColor(...grayText);
    pdf.setFont('helvetica', 'normal');
    
    data.observations.forEach(obs => {
      checkPageBreak(5);
      pdf.text(`- ${obs}`, margins.left + 3, currentY);
      currentY += 5;
    });
    
    currentY += 5;
    addSeparator();
    
    // ==== DAILY LOG TABLE (moved to bottom) ====
    addSectionHeader('Daily Log Summary');
    
    const tableHeaders = ['Date', 'Total Sleep (h)', 'Naps', 'Feed Volume (ml)', 'Feeds'];
    const colWidths = [
      contentWidth * 0.2,
      contentWidth * 0.2,
      contentWidth * 0.15,
      contentWidth * 0.25,
      contentWidth * 0.2
    ];
    
    const drawTableHeader = () => {
      checkPageBreak(8);
      pdf.setFillColor(245, 245, 245); // #f5f5f5
      pdf.rect(margins.left, currentY - 4, contentWidth, 8, 'F');
      pdf.setDrawColor(156, 163, 175); // gray-400
      pdf.setLineWidth(0.5);
      pdf.line(margins.left, currentY + 4, pageWidth - margins.right, currentY + 4);
      
      pdf.setTextColor(...grayText);
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(8);
      let x = margins.left + 2;
      tableHeaders.forEach((header, i) => {
        pdf.text(header, x, currentY);
        x += colWidths[i];
      });
      currentY += 7;
    };
    
    drawTableHeader();
    
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(...grayText);
    pdf.setFontSize(8);
    
    for (let i = 0; i < data.dailyLogs.length; i++) {
      const log = data.dailyLogs[i];
      
      if (currentY + 7 > maxY) {
        addFooter();
        pdf.addPage();
        currentPage++;
        currentY = margins.top;
        drawTableHeader();
      }
      
      if (i % 2 === 0) {
        pdf.setFillColor(249, 250, 251);
        pdf.rect(margins.left, currentY - 4, contentWidth, 7, 'F');
      }
      
      pdf.setDrawColor(229, 231, 235); // gray-200
      pdf.setLineWidth(0.2);
      pdf.line(margins.left, currentY + 3, pageWidth - margins.right, currentY + 3);
      
      let x = margins.left + 2;
      pdf.text(log.date, x, currentY);
      x += colWidths[0];
      pdf.text(log.sleepHours > 0 ? log.sleepHours.toFixed(1) : '—', x, currentY);
      x += colWidths[1];
      pdf.text(log.naps > 0 ? String(log.naps) : '—', x, currentY);
      x += colWidths[2];
      pdf.text(log.feedVolume > 0 ? String(log.feedVolume) : '—', x, currentY);
      x += colWidths[3];
      pdf.text(log.feeds > 0 ? String(log.feeds) : '—', x, currentY);
      
      currentY += 7;
    }
    
    currentY += 5;
    addSeparator();
    
    // ==== MILESTONES ====
    if (data.milestones && data.milestones.length > 0) {
      addSectionHeader('Milestones & Key Changes');
      checkPageBreak(10);
      
      pdf.setDrawColor(156, 163, 175);
      pdf.setLineWidth(0.5);
      pdf.line(margins.left, currentY - 2, pageWidth - margins.right, currentY - 2);
      pdf.line(margins.left, currentY + (data.milestones.length * 5) + 2, pageWidth - margins.right, currentY + (data.milestones.length * 5) + 2);
      currentY += 2;
      
      pdf.setFontSize(9);
      pdf.setTextColor(...grayText);
      pdf.setFont('helvetica', 'normal');
      
      data.milestones.forEach(milestone => {
        checkPageBreak(5);
        pdf.text(`• ${milestone}`, margins.left + 3, currentY);
        currentY += 5;
      });
      
      currentY += 5;
      addSeparator();
    }
    
    // ==== OBSERVATIONS ====
    addSectionHeader('Observations');
    pdf.setFontSize(9);
    pdf.setTextColor(...grayText);
    pdf.setFont('helvetica', 'normal');
    
    data.observations.forEach(obs => {
      checkPageBreak(5);
      pdf.text(`• ${obs}`, margins.left + 3, currentY);
      currentY += 5;
    });
    
    // Add footer to last page
    addFooter();
    
    // Generate PDF
    const pdfBytes = pdf.output('arraybuffer');
    
    return new Response(pdfBytes, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${data.babyName}-pediatrician-summary.pdf"`,
      },
    });
    
  } catch (error) {
    console.error('Error generating PDF:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
