import { useEffect, useMemo } from "react";
import { useActivities, convertToUIActivity } from "@/hooks/useActivities";
import { useHousehold } from "@/hooks/useHousehold";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { TrendChart } from "@/components/TrendChart";
import { SleepChart } from "@/components/SleepChart";
import { getWeekCaption } from "@/utils/share/chartShare";

function formatAge(birthday?: string | null) {
  if (!birthday) return "";
  const dob = new Date(birthday);
  const now = new Date();
  let months = (now.getFullYear() - dob.getFullYear()) * 12 + (now.getMonth() - dob.getMonth());
  const daysIntoMonth = now.getDate() - dob.getDate();
  if (daysIntoMonth < 0) months -= 1;
  const monthsDate = new Date(dob);
  monthsDate.setMonth(dob.getMonth() + months);
  const diffMs = now.getTime() - monthsDate.getTime();
  const weeks = Math.floor(diffMs / (1000 * 60 * 60 * 24 * 7));
  return `${months} months ${weeks} weeks`;
}

export default function WeeklyReport() {
  const { activities, loading } = useActivities();
  const { household } = useHousehold();

  const babyName = household?.baby_name || "Baby";
  const ageText = formatAge(household?.baby_birthday);
  const weekCaption = getWeekCaption(0);

  const uiActivities = useMemo(() => activities.map(convertToUIActivity), [activities]);

  useEffect(() => {
    document.title = `${babyName}’s Weekly Summary Report`;
  }, [babyName]);

  return (
    <main className="min-h-screen bg-background text-foreground print:bg-white print:text-black">
      <div className="max-w-5xl mx-auto px-4 py-6 print:p-0">
        {/* Header */}
        <header className="flex items-start justify-between mb-6 print:mb-4">
          <div>
            <p className="text-sm text-muted-foreground">Parenting Partner</p>
            <h1 className="text-2xl font-bold mt-1">{babyName}’s Weekly Summary Report</h1>
            <p className="text-sm text-muted-foreground mt-1">{babyName} • {ageText}</p>
            <p className="text-sm mt-1">{weekCaption}</p>
          </div>
          <div className="print:hidden">
            <Button variant="outline" onClick={() => window.print()}>Print</Button>
          </div>
        </header>

        <Separator className="my-4" />

        {/* Overview Cards - simple placeholders for quick win */}
        <section className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
          <Card>
            <CardHeader>
              <CardTitle>Feed Overview</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">This section summarizes feeds for the past 7 days.</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Sleep Overview</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">This section summarizes naps for the past 7 days.</p>
            </CardContent>
          </Card>
        </section>

        {/* Trends */}
        <section className="space-y-6 mb-6">
          <h2 className="text-xl font-semibold">Trends</h2>
          <Card>
            <CardHeader>
              <CardTitle>Daily Feed Totals</CardTitle>
            </CardHeader>
            <CardContent>
              <TrendChart activities={uiActivities as any} />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Weekly Sleep Schedule</CardTitle>
            </CardHeader>
            <CardContent>
              <SleepChart activities={uiActivities as any} />
            </CardContent>
          </Card>
        </section>

        {/* Footer */}
        <footer className="text-xs text-muted-foreground mt-8 print:mt-4">
          <Separator className="my-4" />
          <p>Generated by Parenting Partner • {new Date().toLocaleString()}</p>
          <p>For informational use — not a medical record</p>
        </footer>
      </div>
    </main>
  );
}
